Homomorphic XOR and NOT gates
KULeuven-COSIC/FINAL pull request #1
Opened 2022-03-11 13:16 UTC by hilder-vitor

- Created homomorphic XOR and NOT gates.
- Created tests for these gates.
- Refactored tests to instantiate SchemeNTRU a single time because generating the key several times was taking too much time.

2022-03-24 14:19 UTC, iliailia requested changes
Thank you for the changes! I left a few comments where you can simplify the code; the rest looks great!

2022-03-24 14:19 UTC, iliailia commented on include/ntruhe.h
> -     * @param[out] ct_res encryptions of the outuput of the NAND gate
Thanks for fixing these comments!

2022-03-24 14:19 UTC, iliailia commented on src/lwehe.cpp
> +    if (ct_res.a.size() != parLWE.n)
You can simplify here by writing 

```c++
ct_res = ct1 + ct2;
ct_res = ct_res + ct_res;
```

2022-03-24 14:19 UTC, iliailia commented on src/lwehe.cpp
> +    if (ct_res.a.size() != parLWE.n)
Here, you can simplify by writing only
```c++
ct_res = parLwe.delta_base - ct;
```

2022-03-24 14:19 UTC, iliailia commented on src/ntruhe.cpp
> +    if (ct_res.data.size() != parNTRU.n)
You can simplify here by writing 

```c++
ct_res = ct1 + ct2;
ct_res = ct_res + ct_res;
```

2022-03-24 14:19 UTC, iliailia commented on test.cpp
> +    int N_TESTS = 110;
:) Why 110?

2022-03-24 21:09 UTC, hilder-vitor commented
Thanks for the comments. Indeed, the code of those gates are simpler now. I also ran the tests and everything is still working fine, so I think you can merge it now.

2022-03-27 10:12 UTC, iliailia approved these changes
Thanks!

2022-03-27 10:12 UTC, merged